use_frameworks!
target 'NordicDFU_Example' do
  platform :ios, '12.0'
  pod 'iOSDFULibrary', :path => '../'
end

target 'NordicDFU_Tests' do
  platform :ios, '12.0'
  pod 'iOSDFULibrary', :path => '../'
end

target 'macOSDFULibrary_Example' do
  platform :osx, '10.14'
  pod 'iOSDFULibrary', :path => '../'
end
