use_frameworks!
target 'iOSDFULibrary_Example' do
  platform :ios, '9.0'
  pod 'iOSDFULibrary', :path => '../'
end

target 'iOSDFULibrary_Tests' do
  platform :ios, '9.0'
  pod 'iOSDFULibrary', :path => '../'
end

target 'macOSDFULibrary_Example' do
  platform :osx, '10.14'
  pod 'iOSDFULibrary', :path => '../'
end
